import {layout} from '../web/pages.js';
import {states} from './model.js';
export function majorityPage(user:any){
 return layout('Governador e Presidente',`<style>
body.sov-shell{background:#090f1f;color:#fff}.sov-shell .card{background:#121d30;color:#fff;border-color:#34425b}.sov-shell h1,.sov-shell h2,.sov-shell h3,.sov-public .card h3{color:#ffdc35}.sov-shell .muted,.sov-shell .footer{color:#bdc9db}.sov-shell input,.sov-shell select{background:#17263b;color:#fff;border-color:#53627a}.sov-shell .btn.secondary{background:#17263b;color:#fff;border-color:#53627a}.sov-shell th{background:#17263b;color:#c8d3e4}.sov-shell tbody tr:hover{background:#1b2b42}.sov-shell :is(button,input,select):focus-visible{outline:3px solid #ffdc35}
.majority-grid{display:grid;grid-template-columns:330px minmax(0,1fr);gap:18px;margin-top:20px}.majority-map{height:650px;border-radius:12px;background:#142035}.majority-list{max-height:620px;overflow:auto}.majority-list button{display:block;width:100%;text-align:left;background:transparent;color:inherit;border:0;border-bottom:1px solid #354057;padding:14px;cursor:pointer}.majority-list button:hover{background:#21334b}.majority-list small{display:block;color:#bcc7d9}.majority-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:18px 0}.majority-metrics strong{display:block;font-size:26px;color:#ffe044}.majority-status{padding:12px;border:1px solid #485873;border-radius:10px;margin:12px 0}.majority-detail{overflow:auto;margin-top:18px}.majority-detail table{min-width:650px}.majority-tag{background:#fff;color:#111;padding:3px 6px;border-radius:4px;font-size:11px}.majority-search-results button{margin:5px}.majority-toolbar{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px}.sov-shell [hidden]{display:none!important}@media(max-width:800px){.majority-grid{grid-template-columns:1fr}.majority-list{max-height:250px}.majority-map{height:55vh;min-height:360px}.majority-metrics{grid-template-columns:1fr 1fr}.majority-grid summary{padding:12px;cursor:pointer}}</style>
<div class="row"><a class="btn secondary" href="/app">Consultas de deputados e demais recursos</a></div>
<h1>Governador e Presidente</h1><p class="muted">Resultados armazenados de 2026, primeiro turno. Fonte eleitoral: TSE.</p>
<form id="majoritySearch" class="card"><div class="grid">
<label class="field">Cargo<select id="majorityOffice"><option value="3">Governador</option><option value="1">Presidente da República</option></select></label>
<label class="field">Estado<select id="majorityUF"><option value=""></option>${states.map(s=>`<option value="${s.uf}">${s.name} (${s.uf})</option>`).join('')}</select></label>
<label class="field">Candidato<input id="majorityQuery" placeholder="Nome ou número" autocomplete="off"></label></div>
<button class="btn" type="submit">Buscar candidatos</button><div id="majorityResults" class="majority-search-results" role="status" aria-live="polite"></div></form>
<section id="majorityPanel" hidden><h2 id="majorityTitle"></h2><p id="majorityScope"></p>
<div class="majority-metrics"><div class="card">Total oficial do candidato<strong id="majorityTotal"></strong></div><div class="card">Registros municipais presentes<strong id="majorityCoverage"></strong></div><div class="card">Votos válidos / brancos / nulos<strong id="majorityIndicators">Consultando...</strong><small id="majorityIndicatorStatus"></small></div></div>
<div id="majorityStatus" class="majority-status" role="status" aria-live="polite"></div>
<details class="card"><summary>Comparar dois candidatos da mesma eleição</summary><form id="majorityCompareSearch"><label class="field">Segundo candidato<input id="majorityCompareQuery" placeholder="Nome ou número" required></label><button class="btn" type="submit">Buscar para comparar</button></form><div id="majorityCompareOptions"></div><div id="majorityComparison" role="status" aria-live="polite" style="max-height:420px;overflow:auto"></div></details>
<div class="majority-toolbar"><button type="button" class="btn secondary" id="majorityBrazil">Ver Brasil</button><button type="button" class="btn secondary" id="majorityState" hidden>Voltar ao mapa do estado</button><button type="button" class="btn secondary" id="majorityLocation">Minha localização</button><button type="button" class="btn secondary" id="majoritySatellite" aria-pressed="false">Satélite</button><button type="button" class="btn" id="majorityCSV">Baixar dados CSV</button></div><div id="majorityPrint" hidden><h3 id="majorityPrintTitle">MAPA PROFISSIONAL</h3><p id="majorityPrintDescription"></p><div class="row"><button type="button" class="btn" id="majorityES">Baixar mapa SVG vetorial</button><button type="button" class="btn" id="majorityPNG">Baixar mapa PNG A2</button><button type="button" class="btn secondary" id="majorityTable">Baixar relatório complementar paginado</button></div><p id="majorityPrintStatus" role="status" aria-live="polite"></p></div>
<div class="majority-grid"><details open><summary id="majorityListTitle">Municípios e votação</summary><label class="field" id="majorityFilterField">Buscar território<input id="majorityFilter" placeholder="Estado ou município"></label><label class="field">Ordenação<select id="majoritySort"><option value="name">Alfabética</option><option value="votes-desc">Mais votos</option><option value="votes-asc">Menos votos</option><option value="share-desc">Participação no total do candidato</option></select></label><div class="majority-list" id="majorityList"></div></details><div><div class="majority-map" id="majorityMap" aria-label="Mapa eleitoral"></div><p class="muted">Cores: intensidade dos votos disponíveis. Cinza: sem registro completo. Percentuais representam participação no total do candidato, quando disponível.</p><p id="majorityMapStatus" role="status"></p></div></div>
<div class="card majority-detail" id="majorityDetail" hidden><h3 id="majorityDetailTitle"></h3><div class="row"><button class="btn secondary" id="majorityBackMunicipality" type="button">Voltar ao município</button><button class="btn secondary" id="majorityAllSections" type="button">Todas as seções do município</button></div><div id="majoritySections"></div><button type="button" class="btn secondary" id="majorityNext" hidden>Próxima página de seções</button></div>
<p class="muted" id="majorityExteriorHint">Exterior: consulte Ver Brasil e abra o painel específico abaixo. As unidades do exterior nunca são atribuídas a municípios brasileiros.</p><button type="button" class="btn secondary" id="majorityExterior">Consultar unidades eleitorais do exterior</button>
</section><script src="/assets/siga-voto/majority.js"></script>`,user);
}
