const css = "*{box-sizing:border-box}body{margin:0;font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#f4f6f8;color:#151515}a{color:inherit}.wrap{max-width:1100px;margin:auto;padding:28px}.nav{display:flex;justify-content:space-between;align-items:center;padding:20px 0}.brand{font-weight:900;font-size:21px}.card{background:#fff;border:1px solid #e7e7e7;border-radius:20px;padding:24px;box-shadow:0 10px 35px rgba(0,0,0,.05)}.hero{padding:70px 0}.hero h1{font-size:52px;line-height:1;margin:0 0 18px;max-width:750px}.muted{color:#68717a}.btn{display:inline-block;border:0;border-radius:12px;padding:12px 18px;background:#111;color:#fff;text-decoration:none;font-weight:750;cursor:pointer}.btn.secondary{background:#fff;color:#111;border:1px solid #ddd}.row{display:flex;gap:12px;flex-wrap:wrap}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:16px}.field{display:flex;flex-direction:column;gap:6px;margin:12px 0}input,select{padding:13px;border:1px solid #d7dce0;border-radius:10px;font:inherit}.auth{max-width:460px;margin:55px auto}.error{background:#fff1f0;color:#9d1717;padding:12px;border-radius:10px;margin:12px 0}.metric{font-size:34px;font-weight:900}.tag{display:inline-flex;padding:5px 9px;border-radius:999px;background:#edf0f3;font-size:12px}.footer{padding:35px 0;color:#777;font-size:12px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #eee}th{font-size:12px;text-transform:uppercase;color:#68717a}@media(max-width:700px){.hero h1{font-size:38px}.wrap{padding:18px}}";

function esc(v:unknown){return String(v??"").replace(/[&<>"']/g,function(c){return ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"} as any)[c]})}

export function layout(title:string,body:string,user?:any){
  var actions = user ? '<a class="btn secondary" href="/app">Painel</a><form method="post" action="/logout"><button class="btn secondary">Sair</button></form>' : '<a class="btn secondary" href="/login">Entrar</a><a class="btn" href="/cadastro">Assinar</a>';
  return '<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+' | Votos por Seção</title><style>'+css+'</style></head><body><div class="wrap"><div class="nav"><a href="/" class="brand" style="text-decoration:none">Votos por Seção <span class="tag">2026</span></a><div class="row">'+actions+'</div></div>'+body+'<div class="footer">Fonte original dos dados eleitorais: Tribunal Superior Eleitoral. Plataforma independente.</div></div></body></html>';
}

export function homePage(user?:any){
  var buttons = user ? '<a class="btn" href="/app">Abrir aplicativo</a>' : '<a class="btn" href="/cadastro">Criar acesso</a><a class="btn secondary" href="/login">Já sou assinante</a>';
  return layout("Início",'<section class="hero"><h1>Resultados eleitorais de 2026, seção por seção.</h1><p class="muted" style="font-size:19px;max-width:730px">Consulte candidatos, municípios, bairros, zonas, locais de votação e seções em uma base própria construída a partir dos dados oficiais da Justiça Eleitoral.</p><div class="row" style="margin-top:24px">'+buttons+'</div></section><div class="grid"><div class="card"><b>Base 2026</b><p class="muted">Dados oficiais preservados localmente.</p></div><div class="card"><b>Detalhamento</b><p class="muted">Município, bairro, zona, local e seção conforme disponibilidade oficial.</p></div><div class="card"><b>Acesso privado</b><p class="muted">Conta individual e assinatura ativa.</p></div></div>',user);
}

export function authPage(kind:"login"|"cadastro",error=""){
  var extra = kind==="cadastro" ? '<label class="field">Nome<input name="name" autocomplete="name"></label>' : '';
  var err = error ? '<div class="error">'+esc(error)+'</div>' : '';
  return layout(kind==="login"?"Entrar":"Criar conta",'<div class="auth card"><h1>'+(kind==="login"?"Entrar":"Criar conta")+'</h1>'+err+'<form method="post" action="/'+kind+'">'+extra+'<label class="field">E-mail<input type="email" name="email" required autocomplete="email"></label><label class="field">Senha<input type="password" name="password" required minlength="12"></label><button class="btn" style="width:100%">'+(kind==="login"?"Entrar":"Continuar")+'</button></form></div>');
}

export function plansPage(user:any){
  return layout("Planos",'<h1>Escolha seu acesso</h1><div class="grid"><div class="card"><div class="tag">Mensal</div><h2>Assinatura mensal</h2><p class="muted">Acesso enquanto a assinatura estiver ativa.</p><form method="post" action="/checkout"><input type="hidden" name="plan" value="monthly"><button class="btn">Assinar mensal</button></form></div><div class="card"><div class="tag">Pagamento único</div><h2>Acesso permanente</h2><p class="muted">Um único pagamento para manter o acesso.</p><form method="post" action="/checkout"><input type="hidden" name="plan" value="lifetime"><button class="btn">Comprar acesso</button></form></div></div>',user);
}

export function appPage(user:any,active:boolean){
  if(!active) return layout("Aplicativo",'<div class="card"><h1>Assinatura necessária</h1><p class="muted">Sua conta está autenticada, mas ainda não possui uma assinatura ativa.</p><a class="btn" href="/planos">Escolher plano</a></div>',user);
  var body = '<h1>Consulta eleitoral</h1><div class="card"><form id="search"><div class="grid"><label class="field">Candidato<input name="q" placeholder="Nome ou número" required></label><label class="field">Cargo<select name="office"><option value="">Todos</option><option value="1">Presidente</option><option value="3">Governador</option><option value="5">Senador</option><option value="6">Deputado Federal</option><option value="7">Deputado Estadual/Distrital</option></select></label><label class="field">UF<input name="uf" maxlength="2" placeholder="ES"></label></div><button class="btn">Buscar</button></form><div id="results" style="margin-top:20px"></div></div><script>document.getElementById("search").addEventListener("submit",async function(e){e.preventDefault();var f=new FormData(e.target);var p=new URLSearchParams();for(var pair of f.entries()){if(pair[1])p.set(pair[0],String(pair[1]))}var r=await fetch("/api/candidates?"+p.toString());var d=await r.json();var el=document.getElementById("results");if(!r.ok){el.innerHTML="<div class=error>"+d.error+"</div>";return}el.innerHTML="<table><thead><tr><th>Candidato</th><th>Cargo</th><th>UF</th><th>Número</th><th>Partido</th></tr></thead><tbody>"+d.rows.map(function(x){return "<tr><td><b>"+x.ballot_name+"</b></td><td>"+x.office_name+"</td><td>"+x.uf+"</td><td>"+x.number+"</td><td>"+(x.party_abbr||"")+"</td></tr>"}).join("")+"</tbody></table>"});</script>';
  return layout("Aplicativo",body,user);
}

export function adminPage(user:any,stats:any){
  return layout("Administração",'<h1>Painel administrativo</h1><div class="grid"><div class="card"><div class="muted">Usuários</div><div class="metric">'+esc(stats.users)+'</div></div><div class="card"><div class="muted">Assinaturas ativas</div><div class="metric">'+esc(stats.active)+'</div></div><div class="card"><div class="muted">Importações concluídas</div><div class="metric">'+esc(stats.imports)+'</div></div></div>',user);
}
